apiVersion: v1
kind: Secret
metadata:
  name: ca-key-pair
  namespace: cert-manager
  annotations:
    "meta.helm.sh/release-name": {{ .Release.Name }}
    "meta.helm.sh/release-namespace": {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "../../../ca-setup/ca.crt" | b64enc }}
  tls.key: {{ .Files.Get "../../../ca-setup/ca.key" | b64enc }}