apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-html-content
  labels:
    app: {{ .Release.Name }}-hello-nginx
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  index.html: |
    {{ .Values.customHTML | nindent 4 }}